# Generated by Django 4.1.7 on 2023-03-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='courses',
            field=models.ManyToManyField(blank=True, to='base.course'),
        ),
    ]
