# Generated by Django 4.1.7 on 2023-03-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_news_options_alter_myuser_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycourse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_course_images/'),
        ),
    ]
